/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdio.h>
#include "main.h"

RCC_AHB2ENR_t volatile *const pClkCtrlReg   = (RCC_AHB2ENR_t *) 0x4002104C;
GPIOx_MODER_t volatile *const pPortAModeReg = (GPIOx_MODER_t *) 0x48000000;
GPIOx_MODER_t volatile *const pPortBModeReg = (GPIOx_MODER_t *) 0x48000400;
GPIOx_PUPDR_t volatile *const pPortAPupdReg = (GPIOx_PUPDR_t *) 0x4800000C;
GPIOx_IDR_t   volatile *const pPortAInpReg  = (GPIOx_IDR_t *) 0x48000010;
GPIOx_ODR_t   volatile *const pPortBOutReg  = (GPIOx_ODR_t *) 0x48000414;

void init(void);
void delay(void);
void smalldelay(void);
void makeAllRowHigh(void);
void makeRow1Low(void);
void row1LowReadColomns(void);
void makeRow2Low(void);
void row2LowReadColomns(void);
void makeRow3Low(void);
void row3LowReadColomns(void);
void makeRow4Low(void);
void row4LowReadColomns(void);

int main(void)
{
	init();

	while(1)
	{
//		printf("PA5: %d, PA6: %d, PA7: %d, PA9: %d\n", pPortAInpReg->pin_5, pPortAInpReg->pin_6, pPortAInpReg->pin_7, pPortAInpReg->pin_9);

		makeAllRowHigh();

		makeRow1Low();
//		printf("PB1: %d, PB2: %d, PB14: %d, PB15: %d\n", pPortBOutReg->pin_1, pPortBOutReg->pin_2, pPortBOutReg->pin_14, pPortBOutReg->pin_15);

		row1LowReadColomns();

		makeRow2Low();
//		printf("PB1: %d, PB2: %d, PB14: %d, PB15: %d\n", pPortBOutReg->pin_1, pPortBOutReg->pin_2, pPortBOutReg->pin_14, pPortBOutReg->pin_15);

		row2LowReadColomns();

		makeRow3Low();
//		printf("PB1: %d, PB2: %d, PB14: %d, PB15: %d\n", pPortBOutReg->pin_1, pPortBOutReg->pin_2, pPortBOutReg->pin_14, pPortBOutReg->pin_15);

		row3LowReadColomns();

		makeRow4Low();
//		printf("PB1: %d, PB2: %d, PB14: %d, PB15: %d\n", pPortBOutReg->pin_1, pPortBOutReg->pin_2, pPortBOutReg->pin_14, pPortBOutReg->pin_15);

		row4LowReadColomns();

		delay();
	}

}

void init(void)
{
	// 1. Enable the clock for GPIO A and GPIO B
	pClkCtrlReg->gpioa_en = ENABLE;
	pClkCtrlReg->gpiob_en = ENABLE;

	// 2. Make all row IOs mode as OUTPUT
	pPortBModeReg->pin_1  = MODE_OUTPUT;
	pPortBModeReg->pin_2  = MODE_OUTPUT;
	pPortBModeReg->pin_14 = MODE_OUTPUT;
	pPortBModeReg->pin_15 = MODE_OUTPUT;

	// 3. Make all colomn IOs mode as INPUT
	pPortAModeReg->pin_5 = MODE_INPUT;
	pPortAModeReg->pin_6 = MODE_INPUT;
	pPortAModeReg->pin_7 = MODE_INPUT;
	pPortAModeReg->pin_9 = MODE_INPUT;

	// 4. Activate Input pull-up register
	pPortAPupdReg->pin_5 = INPUT_PULLUP;
	pPortAPupdReg->pin_6 = INPUT_PULLUP;
	pPortAPupdReg->pin_7 = INPUT_PULLUP;
	pPortAPupdReg->pin_9 = INPUT_PULLUP;
}

void delay(void)
{
	for (uint32_t i = 0; i < 300000; i++);
}

void smalldelay(void)
{
	for (uint32_t i = 0; i < 30000; i++);
}


void makeAllRowHigh(void)
{
	// Make all row GPIOs as HIGH state
	pPortBOutReg->pin_1 = HIGH;
	pPortBOutReg->pin_2 = HIGH;
	pPortBOutReg->pin_14 = HIGH;
	pPortBOutReg->pin_15 = HIGH;
}

void makeRow1Low(void)
{
	// Make all row GPIOs as HIGH state
	pPortBOutReg->pin_1 = LOW;
	pPortBOutReg->pin_2 = HIGH;
	pPortBOutReg->pin_14 = HIGH;
	pPortBOutReg->pin_15 = HIGH;
}

void row1LowReadColomns(void)
{
	// Scan the colomns
	// Check C1 (PA5) low or high
	if(!(pPortAInpReg->pin_5)){
		// Key is Pressed
		delay();
		printf("1\n");
	}
	// Check C2 (PA6) low or high
	if(!(pPortAInpReg->pin_6)){
		// Key is Pressed
		delay();
		printf("2\n");
	}
	// Check C3 (PA7) low or high
	if(!(pPortAInpReg->pin_7)){
		// Key is Pressed
		delay();
		printf("3\n");
	}
	// Check C4 (PA9) low or high
	if(!(pPortAInpReg->pin_9)){
		// Key is Pressed
		delay();
		printf("A\n");
	}
}

void makeRow2Low(void)
{
	// Make all row GPIOs as HIGH state
	pPortBOutReg->pin_1 = HIGH;
	pPortBOutReg->pin_2 = LOW;
	pPortBOutReg->pin_14 = HIGH;
	pPortBOutReg->pin_15 = HIGH;
}

void row2LowReadColomns(void)
{
	// Scan the colomns
	// Check C1 (PA5) low or high
	if(!(pPortAInpReg->pin_5)){
		// Key is Pressed
		delay();
		printf("4\n");
	}
	// Check C2 (PA6) low or high
	if(!(pPortAInpReg->pin_6)){
		// Key is Pressed
		delay();
		printf("5\n");
	}
	// Check C3 (PA7) low or high
	if(!(pPortAInpReg->pin_7)){
		// Key is Pressed
		delay();
		printf("6\n");
	}
	// Check C4 (PA9) low or high
	if(!(pPortAInpReg->pin_9)){
		// Key is Pressed
		delay();
		printf("B\n");
	}
}

void makeRow3Low(void)
{
	// Make all row GPIOs as HIGH state
	pPortBOutReg->pin_1 = HIGH;
	pPortBOutReg->pin_2 = HIGH;
	pPortBOutReg->pin_14 = LOW;
	pPortBOutReg->pin_15 = HIGH;
}

void row3LowReadColomns(void)
{
	// Scan the colomns
	// Check C1 (PA5) low or high
	if(!(pPortAInpReg->pin_5)){
		// Key is Pressed
		delay();
		printf("7\n");
	}
	// Check C2 (PA6) low or high
	if(!(pPortAInpReg->pin_6)){
		// Key is Pressed
		delay();
		printf("8\n");
	}
	// Check C3 (PA7) low or high
	if(!(pPortAInpReg->pin_7)){
		// Key is Pressed
		delay();
		printf("9\n");
	}
	// Check C4 (PA9) low or high
	if(!(pPortAInpReg->pin_9)){
		// Key is Pressed
		delay();
		printf("C\n");
	}
}

void makeRow4Low(void)
{
	// Make all row GPIOs as HIGH state
	pPortBOutReg->pin_1 = HIGH;
	pPortBOutReg->pin_2 = HIGH;
	pPortBOutReg->pin_14 = HIGH;
	pPortBOutReg->pin_15 = LOW;
}

void row4LowReadColomns(void)
{
	// Scan the colomns
	// Check C1 (PA5) low or high
	if(!(pPortAInpReg->pin_5)){
		// Key is Pressed
		delay();
		printf("*\n");
	}
	// Check C2 (PA6) low or high
	if(!(pPortAInpReg->pin_6)){
		// Key is Pressed
		delay();
		printf("0\n");
	}
	// Check C3 (PA7) low or high
	if(!(pPortAInpReg->pin_7)){
		// Key is Pressed
		delay();
		printf("#\n");
	}
	// Check C4 (PA9) low or high
	if(!(pPortAInpReg->pin_9)){
		// Key is Pressed
		delay();
		printf("D\n");
	}
}



